const pricingStyles=document.createElement('link');pricingStyles.rel='stylesheet';pricingStyles.href='packages-update.css';document.head.appendChild(pricingStyles);
const state={vehicle:'Small Car',service:'Jacky Jones Special Package',condition:'Moderate'};
const serviceContent={
  detail:{kicker:'Refresh. Clean. Renew.',title:'Bring back a clean, comfortable vehicle.',description:'From a vacuum, wash, and wax to a complete top-to-bottom detail, choose the level of care your vehicle needs.',items:['Vacuum & Wash/Wax','Deluxe Package','Jacky Jones Special Package','Large and specialty vehicles'],image:'../assets/services-panel.jpg',alt:'Detailed black performance vehicle',choice:'Jacky Jones Special Package'},
  enhance:{kicker:'Restore. Correct. Refine.',title:'Improve clarity, gloss, and finish.',description:'Paint enhancement and correction services target oxidation, haze, swirls, and other visible defects.',items:['Gloss enhancement','Paint correction','Headlight restoration','Finish consultation'],image:'../assets/poster-detail.jpg',alt:'BoPeePs paint enhancement promotional image',choice:'Paint Correction'},
  protect:{kicker:'Seal. Protect. Maintain.',title:'Make the finish easier to maintain.',description:'Protection services add gloss and help shield exterior surfaces from everyday contamination.',items:['Premium wax','Paint sealants','Ceramic preparation','Maintenance recommendations'],image:'../assets/social-card.jpg',alt:'BoPeePs protection promotional image',choice:'Protection'}
};
function syncSummary(){Object.entries(state).forEach(([key,value])=>{document.querySelectorAll(`[data-summary="${key}"]`).forEach(el=>el.textContent=value);document.querySelectorAll(`[data-form-field="${key}"]`).forEach(el=>el.value=value)})}
function selectChoice(group,button){document.querySelectorAll(`[data-choice-group="${group}"] .choice`).forEach(item=>item.classList.toggle('is-selected',item===button));state[group]=button.dataset.value;syncSummary()}
document.querySelectorAll('[data-choice-group]').forEach(group=>{group.addEventListener('click',event=>{const button=event.target.closest('.choice');if(button)selectChoice(group.dataset.choiceGroup,button)})});
document.querySelectorAll('[data-service-tab]').forEach(tab=>{tab.addEventListener('click',()=>{const content=serviceContent[tab.dataset.serviceTab];document.querySelectorAll('[data-service-tab]').forEach(item=>{const selected=item===tab;item.classList.toggle('is-active',selected);item.setAttribute('aria-selected',String(selected))});document.querySelector('[data-service-kicker]').textContent=content.kicker;document.querySelector('[data-service-title]').textContent=content.title;document.querySelector('[data-service-description]').textContent=content.description;document.querySelector('[data-service-list]').innerHTML=content.items.map(item=>`<li>${item}</li>`).join('');const image=document.querySelector('[data-service-image]');image.src=content.image;image.alt=content.alt;const choose=document.querySelector('[data-service-choose]');choose.textContent=`Choose ${tab.textContent.trim().split(/\s+/)[0]}`;choose.dataset.choice=content.choice})});
document.querySelector('[data-service-choose]')?.addEventListener('click',event=>{state.service=event.currentTarget.dataset.choice||'Jacky Jones Special Package';syncSummary();document.querySelector('#builder').scrollIntoView({behavior:'smooth'})});
document.querySelectorAll('[data-package]').forEach(button=>{button.addEventListener('click',()=>{state.service=button.dataset.package;syncSummary();document.querySelector('#builder').scrollIntoView({behavior:'smooth'})})});
document.querySelector('[data-continue-quote]')?.addEventListener('click',()=>document.querySelector('[data-quote-form]').scrollIntoView({behavior:'smooth'}));
function quoteLines(form){const data=new FormData(form);return['Hi BoPeePs, I would like a detailing quote.',`Name: ${data.get('name')||''}`,`Phone: ${data.get('phone')||''}`,`Email: ${data.get('email')||'Not provided'}`,`Vehicle: ${data.get('vehicleModel')||''}`,`Vehicle type: ${data.get('vehicleType')||state.vehicle}`,`Service: ${data.get('service')||state.service}`,`Condition: ${data.get('condition')||state.condition}`,`Notes: ${data.get('notes')||'No additional notes'}`]}
const form=document.querySelector('[data-quote-form]');const status=document.querySelector('[data-form-status]');
form?.addEventListener('submit',event=>{event.preventDefault();if(!form.reportValidity())return;status.textContent='Opening your text app. You can attach photos before sending.';window.location.href=`sms:+17068976177?body=${encodeURIComponent(quoteLines(form).join('\n'))}`});
document.querySelector('[data-email-quote]')?.addEventListener('click',()=>{if(!form.reportValidity())return;status.textContent='Opening your email app.';const subject=encodeURIComponent('BoPeePs Detailing Quote Request');const body=encodeURIComponent(quoteLines(form).join('\n'));window.location.href=`mailto:bopeepsdetail@gmail.com?subject=${subject}&body=${body}`});
const header=document.querySelector('[data-header]');const menuButton=document.querySelector('[data-menu-button]');const nav=document.querySelector('[data-nav]');
function setHeader(){header?.classList.toggle('scrolled',window.scrollY>12)}
setHeader();window.addEventListener('scroll',setHeader,{passive:true});
menuButton?.addEventListener('click',()=>{const open=nav.classList.toggle('is-open');menuButton.setAttribute('aria-expanded',String(open));header.classList.toggle('open',open)});
nav?.addEventListener('click',event=>{if(event.target.matches('a')){nav.classList.remove('is-open');menuButton.setAttribute('aria-expanded','false');header.classList.remove('open')}});
syncSummary();